import crypto from "node:crypto";
import Razorpay from "razorpay";
import { env } from "./config.js";
import { AppError } from "./core.js";
export type GatewayState = "CAPTURED" | "FAILED" | "PENDING";
export interface PaymentProvider { createOrder(amount: number, currency: string, receipt: string): Promise<{ orderId:string; amount:number; currency:string; keyId?:string }>; verifyPaymentSignature(orderId:string,paymentId:string,signature:string): boolean; fetchPayment(paymentId:string): Promise<GatewayState>; refundPayment(paymentId:string): Promise<{refundId:string}>; verifyWebhook(body: Buffer, signature?: string): boolean; }
export class MockPaymentProvider implements PaymentProvider { async createOrder(amount:number,currency:string,receipt:string) { return {orderId:`mock_order_${receipt}`,amount,currency,keyId:"mock_key"}; } verifyPaymentSignature(orderId:string,paymentId:string,signature:string) { return env.NODE_ENV !== "production" && signature === "mock_signature" || signature === crypto.createHmac("sha256","mock-secret").update(`${orderId}|${paymentId}`).digest("hex"); } async fetchPayment(id:string):Promise<GatewayState> { return id.includes("failed") ? "FAILED" : id.includes("pending") ? "PENDING" : "CAPTURED"; } async refundPayment(id:string) { return {refundId:`mock_refund_${id}`}; } verifyWebhook() { return env.NODE_ENV === "test"; } }
export class RazorpayPaymentProvider implements PaymentProvider { private client = new Razorpay({key_id:env.RAZORPAY_KEY_ID!,key_secret:env.RAZORPAY_KEY_SECRET!}); async createOrder(amount:number,currency:string,receipt:string) { const o=await this.client.orders.create({amount,currency,receipt}); return {orderId:o.id,amount:Number(o.amount),currency:o.currency,keyId:env.RAZORPAY_KEY_ID}; } verifyPaymentSignature(orderId:string,paymentId:string,signature:string) { const expected=crypto.createHmac("sha256",env.RAZORPAY_KEY_SECRET!).update(`${orderId}|${paymentId}`).digest("hex"); return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(signature)); } async fetchPayment(id:string):Promise<GatewayState> { const p=await this.client.payments.fetch(id) as {status:string}; return p.status === "captured" ? "CAPTURED" : p.status === "failed" ? "FAILED" : "PENDING"; } async refundPayment(id:string) { const r=await this.client.payments.refund(id,{}) as unknown as {id:string}; return {refundId:r.id}; } verifyWebhook(body:Buffer,signature?:string) { if(!signature || !env.RAZORPAY_WEBHOOK_SECRET) return false; const expected=crypto.createHmac("sha256",env.RAZORPAY_WEBHOOK_SECRET).update(body).digest("hex"); return crypto.timingSafeEqual(Buffer.from(expected),Buffer.from(signature)); } }
export const paymentProvider: PaymentProvider = env.PAYMENT_PROVIDER === "razorpay" ? new RazorpayPaymentProvider() : new MockPaymentProvider();
