import crypto from "node:crypto";
import { Router, raw } from "express";
import bcrypt from "bcrypt";
import { z } from "zod";
import { asyncRoute, authenticate, authorize, respond, validate, AppError } from "./core.js";
import { Donation, Payment, WebhookEvent } from "./models.js";
import { paymentProvider } from "./payments.js";
import { createDonation, issueTokens, settleDonation, User } from "./services.js";

const auth = Router(); const donations = Router(); const payments = Router(); export const paymentWebhook = Router();
auth.post("/register",validate(z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(10),role:z.enum(["USER","NGO"]).default("USER")})),asyncRoute(async(req,res)=>{ const existing=await User.exists({email:req.body.email}); if(existing) throw new AppError(409,"EMAIL_IN_USE","An account already uses this email"); const u=await User.create({...req.body,passwordHash:await bcrypt.hash(req.body.password,12)}); const tokens=await issueTokens({id:u.id,role:u.role}); respond(res,201,{user:{id:u.id,name:u.name,email:u.email,role:u.role},...tokens},"Registration successful"); }));
auth.post("/login",validate(z.object({email:z.string().email(),password:z.string().min(1)})),asyncRoute(async(req,res)=>{ const u=await User.findOne({email:req.body.email}).select("+passwordHash"); if(!u || !(await bcrypt.compare(req.body.password,u.passwordHash))) throw new AppError(401,"INVALID_CREDENTIALS","Invalid email or password"); if(u.status!=="ACTIVE") throw new AppError(403,"ACCOUNT_UNAVAILABLE","This account is not active"); const tokens=await issueTokens({id:u.id,role:u.role}); respond(res,200,{user:{id:u.id,name:u.name,email:u.email,role:u.role},...tokens}); }));
auth.get("/me",authenticate,asyncRoute(async(req,res)=>{const u=await User.findById(req.auth!.userId); if(!u || u.status!=="ACTIVE") throw new AppError(401,"SESSION_INVALID","Session is no longer valid"); respond(res,200,{user:{id:u.id,name:u.name,email:u.email,role:u.role}}); }));
donations.post("/",authenticate,authorize("USER"),validate(z.object({campaignId:z.string(),amount:z.number().int().positive(),currency:z.literal("INR").default("INR")})),asyncRoute(async(req,res)=>respond(res,201,await createDonation(req.auth!.userId,req.body.campaignId,req.body.amount,req.body.currency),"Donation order created")));
donations.get("/:id/status",authenticate,asyncRoute(async(req,res)=>{const d=await Donation.findById(req.params.id); if(!d || (d.userId.toString()!==req.auth!.userId && req.auth!.role!=="SUPER_ADMIN")) throw new AppError(404,"DONATION_NOT_FOUND","Donation was not found"); const p=await Payment.findOne({donationId:d.id}); respond(res,200,{donationStatus:d.status,paymentStatus:p?.status ?? "CREATED",receiptAvailable:Boolean(d.receiptId),receiptId:d.receiptId,campaignAmountUpdated:d.status==="SUCCESS",createdAt:(d as any).createdAt,updatedAt:(d as any).updatedAt}); }));
payments.post("/verify",authenticate,validate(z.object({donationId:z.string(),paymentId:z.string(),signature:z.string()})),asyncRoute(async(req,res)=>{ const d=await Donation.findById(req.body.donationId); if(!d || d.userId.toString()!==req.auth!.userId || !d.providerOrderId) throw new AppError(404,"DONATION_NOT_FOUND","Donation was not found"); if(!paymentProvider.verifyPaymentSignature(d.providerOrderId,req.body.paymentId,req.body.signature)) throw new AppError(400,"INVALID_PAYMENT_SIGNATURE","Payment verification failed"); const state=await paymentProvider.fetchPayment(req.body.paymentId); const result=await settleDonation(d.providerOrderId,req.body.paymentId,state === "CAPTURED" ? "CAPTURED" : "FAILED"); respond(res,200,result,"Payment verification completed"); }));
paymentWebhook.post("/",raw({type:"application/json"}),asyncRoute(async(req,res)=>{ const body=req.body as Buffer; if(!paymentProvider.verifyWebhook(body,req.header("x-razorpay-signature"))) throw new AppError(400,"INVALID_WEBHOOK_SIGNATURE","Webhook signature is invalid"); const eventId=req.header("x-razorpay-event-id"); if(!eventId) throw new AppError(400,"MISSING_EVENT_ID","Webhook event ID is required"); const payload=JSON.parse(body.toString()); try { await WebhookEvent.create({provider:"razorpay",eventId,eventType:payload.event,payloadHash:crypto.createHash("sha256").update(body).digest("hex")}); } catch(e:any) { if(e?.code===11000) return respond(res,200,{duplicate:true}); throw e; } const entity=payload.payload?.payment?.entity; if(entity?.order_id && entity?.id) await settleDonation(entity.order_id,entity.id,payload.event === "payment.captured" || payload.event === "order.paid" ? "CAPTURED" : "FAILED"); await WebhookEvent.updateOne({provider:"razorpay",eventId},{$set:{status:"PROCESSED",processedAt:new Date()}}); respond(res,200,{received:true}); }));
export const api = Router(); api.use("/auth",auth); api.use("/donations",donations); api.use("/payments",payments);
